# Generated by Django 5.2 on 2025-04-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
