# Generated by Django 5.2 on 2025-04-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
